---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rainban1/shankhabazar.com
    - /bin/cp -R . $DEPLOYPATH
    - cd $DEPLOYPATH && php artisan config:cache
    - cd $DEPLOYPATH && php artisan route:cache
    - cd $DEPLOYPATH && php artisan view:cache
    - cd $DEPLOYPATH && php artisan migrate --force
    - cd $DEPLOYPATH && php artisan storage:link
